plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.mymusic'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.example.mymusic"
        minSdk 26
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    packaging {
        resources {
            pickFirsts += ['META-INF/CONTRIBUTORS.md', 'META-INF/LICENSE.md']
        }
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
    implementation 'androidx.media3:media3-exoplayer:1.9.3'
    implementation 'androidx.media3:media3-common:1.9.3'
    implementation 'androidx.media3:media3-session:1.9.3'
    implementation 'com.google.mlkit:language-id:17.0.6'
    implementation 'com.atilika.kuromoji:kuromoji-ipadic:0.9.0'
}
